id: serverless
name: Serverless / Event-Driven Compute
title: "Serverless Application"
nodes:
  - id: s3
    type: s3
    x: 320
    y: 130
    label: Upload Bucket
  - id: imagelambda
    type: lambda
    x: 580
    y: 130
    label: Image Processor
  - id: eventbus
    type: eventbus
    x: 840
    y: 130
    label: Event Bus
  - id: email
    type: email
    x: 1100
    y: 130
  - id: user
    type: user
    x: 60
    y: 340
  - id: apigw
    type: apigw
    x: 320
    y: 340
  - id: lambda
    type: lambda
    x: 580
    y: 340
    label: Handler Function
  - id: nosqldb
    type: nosqldb
    x: 840
    y: 340
    label: Table
  - id: auth
    type: auth
    x: 320
    y: 550
edges:
  - from: user
    to: apigw
    number: 1
  - from: apigw
    to: auth
    number: 2
  - from: apigw
    to: lambda
    number: 3
  - from: lambda
    to: nosqldb
    number: 4
  - from: user
    to: s3
    number: 5
    lineStyle: dashed
  - from: s3
    to: imagelambda
    number: 6
    lineStyle: dashed
  - from: imagelambda
    to: eventbus
    number: 7
  - from: eventbus
    to: email
    number: 8
